[feat] #169 홈 뷰에 네트워크 에러 핸들링 적용
Team-KeepGoEat/KeepGoEat-AOS pull request #173
Opened 2023-02-25 15:17 UTC by YuBeen-Park

## Related issue 🛠
- #169

## Work Description ✏️
- 홈 뷰에 네트워크 에러 핸들링 적용
- 네트워크 감지해서 Visibility 조정하는 방식으로 구현했습니당!!

## Screenshot 📸
<img src="https://user-images.githubusercontent.com/74285061/221364732-77c713d0-31c2-4fe4-9a2d-8b32928b3f89.png" width="360"/>

## Uncompleted Tasks 😅
- [ ] 전체 뷰에 적용해보진 않았구 홈 뷰에만 일단 맛보기로 테스트해보았습니당

2023-02-26 12:48 UTC, youngjinc requested changes
이제 고려해야할 부분은 홈액티비티 뿐만 아니라 모든 액티비티에서 네트워크 연결 해제 시 에러메세지를 보여줘야합니다! 모든 액티비티의 레이아웃에서 layout_network_error 뷰를 만들기에는 보일러플레이트 코드가 생기게됩니다! 레이아웃을 재사용한다고 하더라도 동일하죠! 어떻게 해결하는 것이 좋을 지 조금 더 생각해봅시다~

2023-02-26 12:48 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
> +    }
콜백 잘 사용하셨습니다!

2023-02-26 12:48 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
> +    private fun terminateNetworkCallback() {
unregisterNetworkCallback 이란 함수명도 좋아보입니다~

2023-02-26 12:48 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
> +    }
onStart와 onStop에서 콜백 등록 해제 좋습니다!

2023-02-26 13:13 UTC, YuBeen-Park commented
흠,, 아무래도 액티비티 만들때마다 에러 뷰를 생성하기엔 코드가 너무 반복되는 문제가 생기겠네용
좀 더 공부해보겠습니다!!
@youngjinc

2023-02-27 14:35 UTC, youngjinc commented
> 흠,, 아무래도 액티비티 만들때마다 에러 뷰를 생성하기엔 코드가 너무 반복되는 문제가 생기겠네용 좀 더 공부해보겠습니다!! @youngjinc

BindingActivity를 활용해봅시다!

2023-05-12 22:09 UTC, youngjinc commented
@YuBeen-Park  pr 닫아주세용!

2023-05-13 00:28 UTC, closed without merging