[feat] 탈퇴 뷰 구현
Team-KeepGoEat/KeepGoEat-AOS pull request #174
Opened 2023-02-27 03:55 UTC by YuBeen-Park

## Related issue 🛠
- closed #172

## Work Description ✏️
- 탈퇴 뷰 구현
- 탈퇴하기 버튼 클릭했을 때 에러 메시지
- 탈퇴 다이얼로그 구현

## Screenshot 📸
<img src="https://user-images.githubusercontent.com/74285061/221470410-f905e34e-1380-4f95-9d5e-cc7643ae42bb.png" width="240"/>
<img src="https://user-images.githubusercontent.com/74285061/221470458-14b3c343-3a9f-4836-b07f-2203d627aaad.png" width="240"/>

## Uncompleted Tasks 😅
- [ ] 코드 리팩토링 필요
- [ ] 다이얼로그 ui 수정 (margin값 같은 거 수정 필요)
- [ ] 키보드 자판에서 키보드 내리는 경우 recyclerView visibility 조정하기

2023-02-28 13:29 UTC, youngjinc reviewed
리뷰 완! 넘넘 고생 많았어용~~

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawViewModel.kt
> +}
요거 그냥 MyViewModel에 그대로두면 어떨까용..?! 마이페이지 안에 있기도 하고 로그아웃 로직이랑 한파일에서 보면 좋을 것 같아서요!

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawReasonAdapter.kt
> +) {
탈퇴 사유들을 리사이클러뷰로 구현하셨군용! 아주 좋습니다~

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +        )
이거 withdrawAdapter에서 init{ } 넣어두고 submitList하면 깔꼼할 것 같습니다~ 서버에서 받아오는 데이터도 아니고 항상 동일한 값이니까 어뎁터 내부에서 들고있어도 좋을 것 같아서요~

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +            }
분기처리 장인이시네용 👍

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +        binding.etOtherReason.setOnFocusChangeListener { _, focused ->
사용되지 않는 변수 "_"로 표기 아주 좋습니다~

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +        })
이거 뷰모델에서 otherReason과 isValidOtherReason로 추가해서 데이터바인딩으로 isValidOtherReason의 true 여부에 따라 에러메세지 텍스트뷰의 visibility를 조절하시면 코드가 깔꼼할 것 같습니다~
```kotlin
val otherReason = MutableStateFlow<String>("")
val isValidOtherReason: StateFlow<Boolean>
        get() = otherReason.map { reason ->
            !reason.isNullOrBlank()
        }.toStateFlow(viewModelScope, false)
```

```xml
<TextView
   android:id=@+id/tv_ withdraw_edittext_error
   app:visibility=@{viewModel.isValidOtherReason} />
```

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +    }
여기서 tvWithdrawEdittextError visibility 조절이 필요한가용?!

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/res/layout/activity_withdraw.xml
> +            android:id="@+id/tv_withdraw_edittext_error"
```suggestion
            android:id="@+id/tv_other_reason_error_msg"
```

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/res/layout/activity_withdraw.xml
> +            android:textCursorDrawable="@drawable/shape_cursor"
커서 커스텀까지 좋습니다~

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/domain/model/WithdrawReason.kt
> +)
해당 파일은 뷰에서만 사용되는 데이터 클래스 인것 같습니다! 위치를 presentation>model로 변경해주세용

2023-02-28 13:29 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/type/WithdrawCheckType.kt
> +        R.style.TextAppearance_System4,
클릭됐을 때랑 클릭되지 않았을 때 체크박스 아이콘은 selector를 이용해봐도 좋겠습니다! 그리고 택스트 컬러도 selector 사용도 좋을 것 같구 텍스트 스타일만 데이터바인딩해보면 어떨까합니다!

2023-03-02 05:08 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawViewModel.kt
> +}
넹! 그러면 탈퇴 관련된 로직만  MyViewModel로 옮기고 그 WithDrawActivity에 데이터바인딩할 변수들만 뷰모델에 남겨두는 식으로 수정하면 될까용??

2023-03-02 08:18 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +    }
탈퇴 버튼을 눌렀을 때 edittext 확인해서 에러 메시지 띄우는 걸로 알고 있어용!
근데 이렇게만 하면 에러 메시지를 탈퇴 버튼 눌렀을 때만 확인해서 다른 경우(한번 에러 경고 뜬 후 다시 입력한 경우)를 추가해서 했어요!
이 부분은 기.디 한번 더 확인해보는게 좋을까요??

2023-03-02 08:18 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/domain/model/WithdrawReason.kt
> +)
넹!

2023-03-02 08:18 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/type/WithdrawCheckType.kt
> +        R.style.TextAppearance_System4,
오 한번 수정해보겠습니당!

2023-03-02 09:02 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawViewModel.kt
> +}
변수들도 전부 마이뷰모델로 옮기는 것이 어떨까용?!

2023-03-02 09:12 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +    }
지금 텍스트필드 입력값이 변경될 때도 입력값 유효성 검증을해서 에러메세지 가시성을 조절해주고 있는 것 같은데요!
탈퇴 버튼 누를 때 텍스트필드 확인해서 에러메세지 띄우는 것이라면 위 과정은 필요없지 않나용?!! 
탈퇴버튼 누를 때만인지 입력값 변경될때마다 검증을 해야하는지가 궁금합니다! 기디팀에서 전달 사항이 없었다면 서면 확인 부탁드려요~
제가 앞서 질문을 남긴 이유는 이미 입력값 변경될 때마다 검증을 수행했기 때문에 탈퇴 버튼을 눌렀을 때 다시 유효성 검증을 하지 않아도 되지 않는가 해서 질문 남겼습니당!

2023-03-02 09:14 UTC, youngjinc commented
hidden conversation도 확인해주세용

2023-03-02 09:26 UTC, youngjinc commented
그리고 키보드 내려갔을 때 뷰의 visibility를 조절하는 것은 
editText의 포커스가 떠났을 때 visibility룰 조정하는 걸로도 대체가 가능할 것 같은데요! ”setOnFocusChangeListener“ 
대체 불가하다면 키보드 상태를 감지하는 것이 좋아보입니당! 
[keyboard show/hide event handling](https://stackoverflow.com/questions/4312319/how-to-capture-the-virtual-keyboard-show-hide-event-in-android)

2023-03-03 00:07 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +    }
넹!! 기디팀에 한번 확인해보고 그 내용으로 수정하겠습니당!!

2023-03-03 00:08 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawViewModel.kt
> +}
좋아용 그러면 MyViewModel에서 구현할게용!!

2023-03-11 01:57 UTC, youngjinc requested changes
리뷰 확인해주세용!

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/type/WithdrawCheckType.kt
> +        R.style.TextAppearance_System4,
클릭됐을 때랑 클릭되지 않았을 때를 구분하는 enum class가 맞을까용?!
그렇다면 상수값이 두개이고, 클릭 여부를 판단하는 것이기 때문에 Boolean 타입을 이용해볼 수 있을 것 같고 View의 isSelected를 활용해서 클릭여부를 설정하고, 값을 읽어올 수도 있습니다~

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +        }
하위버전은 대응되나용?!

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +    val isOtherReasonSelected get() = _isOtherReasonSelected.asStateFlow()
일단 직접 입력이 선택되었는지 판단할 때 Boolean값으로 판단하는군용! 현재 탈퇴뷰에서는 5가지 사유가 있고, 추후(QA기간에) 이 중 어떤 사유를 선택했는지 이벤트 로그를 추가할 것입니다! 이를 고려해서 Boolean대신에 enum class로 어떤 사유를 클릭했는지 판별하는 것이 좋아보입니다!

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +        }
```suggestion
        binding.btnWithdraw.setOnClickListener {
            if (!binding.etOtherReason.text.isNullOrBlank() || !isOtherReasonSelected.value)
                WithdrawDialogFragment().show(supportFragmentManager, "withDrawDialog")
        }
```

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/model/WithdrawReason.kt
> +)
isClicked 제거하고 reason만 따로 분리해서 enum class로 만드는 것이 좋겠습니다~ isClicked는 View의 isSelected 속성을 사용해봅시다~

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawReasonAdapter.kt
> +        }
```suggestion
            binding.layoutWithdrawReason.setOnClickListener {
                // TODO 체크박스 이미지 및 탈퇴 사유 텍스트뷰의 isSelected = ! isSelected 조절하기
        }
```

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawReasonAdapter.kt
> +    ListAdapter<WithdrawReason, RecyclerView.ViewHolder>(
```suggestion
class WithdrawReasonAdapter(context: Context) :
    ListAdapter<WithdrawReason, WithdrawReasonAdapter.WithdrawViewHolder>(
```

해당 어뎁터는 멀티뷰홀더를 사용할 여지는 없어보입니다~ 요렇게 바꿔주세용!

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawReasonAdapter.kt
> +    }
```suggestion
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): WithdrawViewHolder {
        if (!::inflater.isInitialized)
            inflater = LayoutInflater.from(parent.context)
        return WithdrawViewHolder(ItemWithdrawBinding.inflate(inflater, parent, false))
    }
```

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawReasonAdapter.kt
> +    }
```suggestion
    override fun onBindViewHolder(holder: WithdrawViewHolder, position: Int) {
                holder.bind(currentList[position])
    }
```

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/res/layout/activity_withdraw.xml
> +            app:title="@{context.getString(R.string.withdraw)}" />
```suggestion
            app:title="@{@string/withdraw}" />
```

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/res/layout/activity_withdraw.xml
> +            android:visibility="@{viewModel.isKeyboardVisible ? view.GONE : view.VISIBLE}"
```suggestion
            app:visibility="@{!viewModel.isKeyboardVisible}"
```

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/res/layout/activity_withdraw.xml
> +                android:src="@{viewModel.isOtherReasonSelected? context.getDrawable(R.drawable.ic_checkbox_checked) : context.getDrawable(R.drawable.ic_checkbox_default)}"
```suggestion
                android:src="@{viewModel.isOtherReasonSelected? @drawable/ic_checkbox_checked : @drawable/ic_checkbox_default}"
```

2023-03-11 01:57 UTC, youngjinc commented on app/src/main/res/layout/activity_withdraw.xml
> +                android:textColor="@{viewModel.isOtherReasonSelected? context.getColor(R.color.orange_600) : context.getColor(R.color.gray_700)}"
```suggestion
                android:textColor="@{viewModel.isOtherReasonSelected? @color/orange_600 : @color/gray_700}"
```

2023-03-12 14:50 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
> +        }
하위버전은 대응안되는 상태입니다!

2023-03-14 23:14 UTC, youngjinc approved these changes
확인 완! 고생했어용 :) 머지해주세요 ~~

2023-03-14 23:14 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/model/WithdrawReason.kt
> +enum class WithdrawReason(
아주 좋습니당 :)

2023-03-15 00:54 UTC, merged