[feat] 목표 보관함의 목표 삭제 기능 구현
Team-KeepGoEat/KeepGoEat-AOS pull request #176
Opened 2023-02-27 13:16 UTC by Dan2dani

## Related issue 🛠
- closed #175 

## Work Description ✏️
- 보관함 목표 삭제 ui 디자인
- 보관함 목표 삭제 기능 구현(api 연동 x)

2023-02-27 14:43 UTC, youngjinc approved these changes
리뷰 완! 고생하셨습니다~

2023-02-27 14:43 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +            }
삭제뷰 visibility가 Gone인지 여부에 따라서 visibility 조절 잘하셨습니다~
외부 영역 클릭시에도 삭제뷰의 visibility 조절이 필요할 수도 있을 것 같네요~ 기디팀에 질문을 남겨봅시다!

2023-02-27 14:43 UTC, youngjinc commented on app/src/main/res/drawable/ic_keep_detail.xml
> +      android:fillColor="#CCCACA"/>
여기 파일명을 ic_more은 어떠신가용?! 
이 버튼을 눌렀을 때 추후 삭제 뿐만 아니라 다른 메뉴도 있을 수 있습니다~ 
그런 점을 고려한다면 네이밍이 (메뉴)더보기가 더 좋을 것 같네용!

2023-02-27 14:43 UTC, youngjinc commented on app/src/main/res/layout/item_achieved_goal.xml
> +        <androidx.appcompat.widget.AppCompatButton
AppCompatButton -> MaterialButton은 어떠신가요~

2023-02-27 14:50 UTC, Dan2dani commented on app/src/main/res/drawable/ic_keep_detail.xml
> +      android:fillColor="#CCCACA"/>
좋습니당!! 수정하겠씁니당!

2023-02-27 14:50 UTC, Dan2dani commented on app/src/main/res/layout/item_achieved_goal.xml
> +        <androidx.appcompat.widget.AppCompatButton
좋습니당!

2023-02-27 14:50 UTC, Dan2dani commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +            }
내일 질문해보겠습니당 >...<

2023-03-07 05:57 UTC, youngjinc requested changes
리뷰 확인해주세요! 수고가 많아용!!

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
> +        goalAdapter = AchievedGoalAdapter(this, viewModel)
뷰모델이 클릭 리스너 인터페이스를 상속받았군요...!
뷰모델의 목표 삭제 함수를 호출하는 Activity의 함수를 넘겨봅시다!
HomeActivity나 목표 삭제 관련된 뷰에서 목표 삭제 로직을 참고해보면 좋을 것 같습니다~

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
> +    }
1. 일단 onTouchEvent로는 자식뷰인 리사이클러뷰의 터치 이벤트를 감지할 수 없다고 하셨죵?! 그렇다면 dispatchTouchEvent로 바꿔봅시다!
2. 그리고 함수 내부에서 for문으로 리사이클러뷰 내 모든 아이템의 삭제버튼에 접근하고 있는데요! for문을 돌아 모두 검사하는 로직보다는 어뎁터 내에서 삭제뷰가 보이는 아이템 객체를 저장하는 변수를 두고, 외부 영역 터치 시에 아이템 객체 변수가 null값이 아니면 삭제뷰가 보인다는 뜻이니 해당 아이템의 포지션을 구해서 해당 포지션만 삭제뷰가 보이지 않도록 ui를 업데이트 해보는 방식도 있겠습니다~ 이때 삭제뷰를 보이지 않도록 ui를 업데이트했으니 삭제뷰가 보이는 아이템 객체 변수는 null이 되어야할 것입니다!

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
> +                    finish()
오호라.. 삭제한 후 다시 액티비티를 띄워서 목표 불러오기 api를 다시 호출하는군요..! 우선 액티비티를 다시 띄우면서 애니메이션이 적용되기 때문에 ui가 업데이트가 부자연스러워 보일 수 있습니다~ 좀 더 부드럽게 업데이트를 하기 위해서는 삭제된 아이템만 깔꼼하게 삭제하면 더 좋을 것 같네요!! 액티비티에서 뷰모델의 목표 삭제 함수를 호출할 것이고, 목표 아이템 리스트를 갱신(삭제 반영)해야할 것입니다! 아이템이 변경되면 액티비티에서는 아이템 리스트의 변경을 감지하고 변경됐을 때 adapter의 아이템을 변경된 아이템으로 갱신해야합니다! 이때 리스트 어뎁터면 submitList가 될 수도 있고, 리사이클러뷰 어뎁터면 notifyItemRemoved()나 notify~~()함수를 호출하면 됩니다!

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
> +
```suggestion
```

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +    private val listener: updateGoalIdListener
클릭 이벤트를 핸들링하는 함수를 넘겨봅시다! 힌트는 고차함수랍니다! 
인터페이스를 따로 만들지 않아도 되고, 인터페이스를 상속받아 함수를 구현하지 않아도 됩니다! 다른 어뎁터 코드도 함 참고해보시면 좋을 것 같네요~

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +                listener.updateGoalId(data)
어뎁터의 생성사 파라미터로 context를 전달하지 않고, 액티비티에서 다이얼로그 보여주는 함수(showDeleteDialog())를 고차함수로 전달하는 방법이 있겠습니다~
아님 뷰의 콘텍스트를 사용해도 되긴합니다..!

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +    private val context: Context,
```suggestion
```

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +    inner class AchievedGoalViewHolder(private val binding: ItemAchievedGoalBinding) :
```suggestion
    class AchievedGoalViewHolder(private val binding: ItemAchievedGoalBinding) :
```
inner class는 정말 필요하지 않은 이상 사용하지 않는 것이 좋습니다! 아래 링크를 참고해보시면 좋을 것 같습니다~ onBind에서 필요한 context와 같이 파라미터가 추가로 더 필요하다면 data넘기듯이 파라미터로 전부 넘기면 되겠습니다~
[Kotlin과 Java의 Nested and Inner Classes를 알아보고, Nested classes를 왜 사용해야 하는지 알아본다.](https://thdev.tech/kotlin/2020/11/17/kotlin_effective_11/)

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +
이 함수는 무슨 용도인가요?!

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/res/layout/activity_achieved_goal.xml
> +                android:text="더이상 기록하지 않는 목표는 보관해요."
텍스트는 전부 추출해주세용!

2023-03-07 05:57 UTC, youngjinc commented on app/src/main/res/layout/activity_achieved_goal.xml
> +                android:fontFamily="@font/pretendard_b"
피그마에서 서체 스타일이 적용되어있지 않았나용?! 고렇다면 스킵~

2023-03-07 06:05 UTC, Dan2dani commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +
goalId를 알아야 목표를 삭제할 수 있어서, goalId를 받아오기 위한? 함수입니다 ..!!

2023-03-07 06:16 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +
고차함수로 아이템 아이디 값을 파라미터로 넘깂시다! 즉 삭제시 호출할 액티비티에서 함수(고차함수로 넘길 것임)의 파라미터에 삭제할 아이템 아이디를 넣을 것이니 해당 아이디를 가지고 뷰모델의 삭제 함수를 호출하면 되겠죠! 뷰모델의 삭제함수도 파라미터로 goal 아이디를 받으면 되겠습니다~ 이렇게되면 해당 함수는 필요없어질 것 입니다!

2023-03-07 07:25 UTC, Dan2dani commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +
해당 아이디를 파라미터로 넘기기 위해서는, 아이디 값을 알고 있는 goalAchievedAdatper에서 고차함수를 생성자로 해 넘겨야하고 이는(어뎁터)  activity에서 생성되지만, 이 goalId를 가지고 보관되어 있는 목표를 삭제하는 행동은 dialog에서 해야하는데,, 이를 어떻게 해야할까용 ! ? ㅜㅜ

저는 그래서 원래 activity의 '삭제하기'버튼을 눌렀을 때 해당 목표의 id를 파라미터(고차함수)로 전달 받아 goalId를 업데이트 하려고 했습니다..!

2023-03-07 08:56 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +
목표를 삭제하는 행동은 dialog에서 꼭 하지 않아도 됩니다! AchievedGoalActivity에서 삭제하는 함수(ex. fun deleteAchievedGoal(goalId: Int))를 만들고, 해당 함수에서 뷰모델의 목표 삭제 함수를 호출해도 됩니다! 이 함수는 goalAchievedAdatper의 생성자 파라미터로 넘기고, adapter에서 goalId를 알고 있기 때문에 어뎁터 > 뷰홀더 클래스 > onBind() > 삭제하기 버튼의 클릭 리스너에서 액티비티에서 전달받은 함수(Int) -> Unit을 호출해주시면 액티비티의 함수가 실행됩니다! int값 goalId는 아래와 같이 파라미터로 전달하면 되겠죵!

```kotlin
onBind(data: AchievedGoal, deleteAchievedGoal: (Int)-> Unit) {
   deleteAchievedGoal(data.id)
}
```

유빈이가 작성한 HomeGoalAdapter와 HomeActivity랑 동일한 로직입니다~

2023-03-07 11:16 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +
고렇다면! 다이얼로그 띄우는 함수를 Activity에 만들고 이 함수를 goalAchievedAdatper의 생성자 파라미터로 넘기면 삭제하기 클릭 시 해당 함수를 호출합니다! 해당 함수에서는 어뎁터에서 전달받은 goalId를 다이얼로그 띄울 때 bundle로 전달해서 yes버튼을 클릭하면 다이얼로그에서 뷰모델의 삭제 함수를 호출하는 방식도 있습니다! 뷰모델의 삭제 함수의 파라미터로 goalId를 받으면 되겠죵?!

```kotlin
private fun showDeleteGoalDialog(goalId: Int) {
        KeepDeleteDialogFragment().apply {
            arguments = Bundle().apply {
                putInt(ARG_DELETE_GOAL_ID, goalId)
            }
        }.show(supportFragmentManager, "KeepDeleteDialog")
    }
```

2023-03-10 04:44 UTC, youngjinc approved these changes
리뷰 완! 조금 만 더 정리하면 좋을 것 같아용!! 모두 반영되면 바로 머지해주세용~

2023-03-10 04:44 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
> +        const val GOAL_ID = "goalId"
```suggestion
        const val ARG_GOAL_ID = "goalId"
```

2023-03-10 04:44 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +    private val showKeepDeleteDialog: (Int) -> Unit,
고차함수를 마스터하셨군용~~ 👍👍 아쥬 좋습니다 :)

2023-03-10 04:44 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +            }
가독성 넘넘 좋습니당 👀 💗

2023-03-10 04:44 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +    }
```suggestion
    fun setGoalList(goals: List<AchievedGoal>) {
        this.goalList = goals
        notifyDataSetChanged()
    }
```

2023-03-10 04:44 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
> +    private var keepGoalList: MutableList<AchievedGoal> = mutableListOf()
```suggestion
    private var goalLists: MutableList<AchievedGoal> = mutableListOf()
```

2023-03-10 04:44 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/KeepDeleteDialogFragment.kt
> +        goalId = arguments?.getInt("goalId")
```suggestion
        goalId = arguments?.getInt(ARG_GOAL_ID)
```

2023-03-10 04:44 UTC, youngjinc commented on app/src/main/res/layout/activity_achieved_goal.xml
> +                android:text="더이상 기록하지 않는 목표는 보관해요."
코멘트 확인해주세용

2023-03-11 05:26 UTC, youngjinc approved these changes
리팩토링 때 반영해주세용! 머지합시당~

2023-03-11 05:26 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/KeepDeleteDialogFragment.kt
> +    }
```suggestion
    companion object {
        private const val ARG_GOAL_ID = "goalId"
    }
```
해당 파일에서만 사용되는 변수라면 private를 붙입시다!

2023-03-11 05:26 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +        _goalId.value = id
```suggestion
```

2023-03-11 05:26 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
> +    val goalId get() = _goalId.asStateFlow()
```suggestion
```

2023-03-11 08:09 UTC, merged