[fix] 이모지 입력되었을 때 2글자로 인식되는 오류 수정
Team-KeepGoEat/KeepGoEat-AOS pull request #235
Opened 2023-05-03 11:41 UTC by YuBeen-Park

## Related issue 🛠
- #230

## Work Description ✏️
- getStringLength 함수 이용해서 현재 글자수 보여주는 로직 구현

## Screenshot 📸
<img src="" width="360"/>

## Uncompleted Tasks 😅
- [ ] 기존에 EditText에서 maxLength를 이용해서 최대 글자수를 제한하고 있었는데 이모지는 제한하지 못하는 로직 수정

2023-05-03 11:49 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
> +            }
이 로직으로는 아직 완벽하게 해결 못한 상태입니다!
15글자를 넘었을 때 일반 문자는 제어가 가능한데
마지막 글자가 이모지인 상태로 15글자가 넘으면 이모지가 삭제되지 않습니다,,,

그리고 막 연타해서 입력했을 때 갑자기 글자수가 두배씩 늘어나는? 버그가 있습니다...

2023-05-03 12:12 UTC, youngjinc requested changes
넘넘 고생 많으셨어용~~ 리뷰 확인해주세요!

2023-05-03 12:12 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
> +            }
15글자를 초과했을 때 dropLast(1) 로 마지막 한글자를 삭제하게되면 커서가 맨 앞으로 이동하지 않나용 ?! 그리고 앞으로 EditText에서 이모지 입력을 허용하고 그때마다 maxLength로 글자수 제한을 걸어야한다면 해당 로직을 모든 파일에서 사용할 수 있도록 분리를 하는 것이 좋아보입니다~ 바인딩 어뎁터 파일도 좋구용 :)

그리고 InputFilter의 사이즈를 정해주어야 합니다! InputFilter를 사용해서 15글자로 제한해도 유저가 15글자에서 더 입력하면 버퍼에 저장되기 때문에 14번 인덱스 즉, 마지막 문자열을 지우고 싶어도 버퍼에 저장된 글자 수 + 1 번만큼 delete 키로 지워야 마지막 글자를 삭제할 수 있습니다.. [자세한 내용은 클릭해서 코멘트를 참고해주세용!](https://stackoverflow.com/a/27980970)

아래 로직은 제가 함 작성해봤는데 테스트 했을 때 기존 maxLength와 동일하게 작동하는 걸 확인했습니다! 참고해주세요~

```kotlin
/** 시스템이 인식하는 글자 수를 사용자가 인식하는 글자 수로 변환해서 글자 수 범위에 따라 maxLength 를 설정 */
@BindingAdapter("maxLen")
fun EditText.cutTextToMaxLength(maxLength: Int) {
    val filterArray = arrayOfNulls<InputFilter>(1)
    addTextChangedListener {
        val str = text.toString()
        when (str.getGraphemeLength()) {
            // 1. 실제 글자 수가 maxLength 미만일 때, 시스템이 인식한 글자 수는 maxLength 이상인 경우를 고려해서
            // 글자를 더 입력할 수 있도록 maxLength 를 최대 길이(* 2 : 시스템에서 한글자가 최대 두글자로 잡힘)로 설정.
            in 0 until maxLength ->
                filters = filterArray.apply { this[0] = LengthFilter(maxLength * 2) }

            // 2. 실제 글자 수가 maxLength 와 동일할 때, maxLength 를 현재 시스템이 인식한 글자수로 설정.
            maxLength ->
                filters = filterArray.apply { this[0] = LengthFilter(str.length) }
        }
    }
}
```

2023-05-03 12:12 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/util/extension/StringExt.kt
> +fun String?.getStringLength(): Int {
함수에 대한 간략한 설명을 주석으로 작성해주시면 좋을 것 같아용~

2023-05-03 12:12 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/util/extension/StringExt.kt
> +    val it: BreakIterator = BreakIterator.getCharacterInstance()
```suggestion
    if (this == null) return 0
    val it: BreakIterator = BreakIterator.getCharacterInstance()
```
빠르게 화면 진입했을 때 목표 음식(goalFood: String?)이 초기화 되지 않은 경우 null일 것이고, 7번라인에서 setText할 때 NPE 발생할 것입니다! 널처리 해주는 것이 좋아보이네용~

2023-05-03 16:39 UTC, YuBeen-Park reviewed
리뷰 고마워용!!
이 문제 해결하고 다른 리팩토링이랑 같이 수정해서 pr 날려보겠습니다~

2023-05-03 16:39 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/util/extension/StringExt.kt
> +    val it: BreakIterator = BreakIterator.getCharacterInstance()
넹! 널처리 적용하도록 하겠습니당~~

2023-05-03 16:39 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
> +            }
우선 dropLast 사용했을 때 커서는 맨 뒤에 그대로 있었어욤!!

이 방식은 0~15이내 글자 수 일때는 30까지로 최대 길이를 늘려주고 15가 되었을 때 현재 글자수를 max로 인식하게끔 해주는 로직으로 이해했는데 맞을까용??

그리구 제가 여기저기 찾아보다가 알게 된건데 이모지의 길이가 2가 아닌 경우들도 있더라구요!
그런 경우들을 처리하려고 16번째 글자를 빼는 로직을 먼저 생각했었는데 저희 서비스에서 사용할 (음식 관련!)이모티콘들에 해당되진 않을거 같긴 해용!

암튼! 영진이가 구현해준 함수로 적용해서 내일 밤에 다시 pr 날려보겠습니당~~

2023-05-04 01:18 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
> +            }
이해하신 방식이 맞습니다~ 그리고 이모지가 2가 아닌 경우가 있다라고 한다면 아래 방식이 좋을 것 같아요~
when절을 삭제하고 `filters = filterArray.apply { this[0] = LengthFilter(maxLength + (str.length - str.getGraphemeLength())) }` 해당 코드를 추가하는거죵!

```kotlin
@BindingAdapter("maxLen")
fun EditText.cutTextToMaxLength(maxLength: Int) {
    val filterArray = arrayOfNulls<InputFilter>(1)
    addTextChangedListener {
        val str = text.toString()
        filters = filterArray.apply { this[0] = LengthFilter(maxLength + (str.length - str.getGraphemeLength())) }
    }
}
```

2023-05-05 02:05 UTC, merged