Feat onboarding view
Team-KeepGoEat/KeepGoEat-AOS pull request #25
Opened 2023-01-04 04:43 UTC by Dan2dani

## Related issue 🛠
- closed #이슈넘버

## Work Description ✏️
- 온보딩뷰 구현

## Screenshot 📸
<img src="" width="360"/>

## Uncompleted Tasks 😅
- [ ] 온보딩 뷰  1번 이미지 해결
- [ ] 뷰페이저 에니메이션 해결

2023-01-04 05:13 UTC, youngjinc requested changes
고생하셨어요~~ 리뷰 확인해주세용!

2023-01-04 05:13 UTC, youngjinc commented on app/src/main/res/drawable/img_onboarding_3.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
png로 다운받아주세용!

2023-01-04 05:13 UTC, youngjinc commented on app/src/main/AndroidManifest.xml
>              android:exported="true"
기존에 GoalDetailTestActivity는 테스트용으로 사용되는 Activity입니당! 해당 Activity는 그대로 두고 OnboardingActivity새로 추가해주세요~

2023-01-04 05:13 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingAdapter.kt
> +class OnBoardingAdapter(fa: FragmentActivity) : FragmentStateAdapter(fa) {
뷰페이저의 어뎁터를 FragmentStateAdatper 대신에 ListAdapter나 RecyclerView.Adapter로 사용해주세요~ 프래그먼트를 여러개 만들지 않고 구현이 가능할 것 같아용! 리사이클러뷰 사용하듯이 item레이아웃 만들어두고, 각 1, 2, 3번 화면에서 보일 이미지리소스나 텍스트를 해당 레이아웃의 텍스트, 이미지뷰 속성으로 지정해주시면 좋을 것 같습니다~

아래 코드를 참고해보셔도 좋습니다~
https://github.com/Health-Food-Me/Health-Food-Me-Android/blob/develop/app/src/main/java/org/helfoome/presentation/common/PhotoSlideAdapter.kt

https://github.com/Health-Food-Me/Health-Food-Me-Android/blob/develop/app/src/main/java/org/helfoome/presentation/common/ImageViewerActivity.kt

2023-01-04 05:13 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/FragmentOnBoardingFirst.kt
> +}
위 코멘트를 확인하신 후 필요없어진 파일들은 삭제 부탁드려용~

2023-01-04 05:13 UTC, youngjinc commented on app/src/main/res/layout/fragment_onboarding_1.xml
> +
ViewPager에 TabLayout을 연결하시고 TabLayout의 Indicator 속성을 사용해서 구현하시면 좋을 것 같습니다~
1, 2, 3페이지에서 중복으로 나타나는 indicator들을 표시하지 않아도 뷰페이저가 있는 레이아웃에서 해당 뷰를 한번만 추가해주고, 각 페이지에서는 변하는 부분 즉, 표시한 부분만 보여주면 될 것 같아용!
<img width="848" alt="스크린샷 2023-01-04 오후 2 10 30" src="https://user-images.githubusercontent.com/48701368/210488526-3fa2f598-e806-4b98-8dcb-156408f72073.png">

그리고 페이지 번호마다 버튼에 보여지는 텍스트나 3페이지에서는 건너뛰기 텍스트가 보이지 않는데 이것은 페이지가 변할 때 마다 텍스트 값을 변경해주고, 건너뛰기 버튼의 visibility를 조절하면 좋을 것 같네용! 힌트는 registerOnPageChangeCallback 입니다~

2023-01-04 14:30 UTC, YuBeen-Park reviewed
좋습니다~~~
수고하셨어용

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingActivity.kt
> +        viewPager.adapter = adapter
val viewPager로 따로 변수로 정의하지 않고 binding을 생략할 수 있는 방법이 있어용!!
```kotlin
with(binding){
   viewPager.isUserInputEnabled = false
   viewPager.adapter = adapter
}
```
요런식으로 변수 설정 없이 삭제 가능합니당!

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingAdapter.kt
> +        return OnBoardingViewHolder(binding)
binding을 따로 변수로 하지 않고 넣어줘도 좋을거 같아요

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingAdapter.kt
> +        (holder as OnBoardingViewHolder).bind(currentItem)
영진이가 알려준건데 (holder as OnBoardingViewHolder) 대신
![image](https://user-images.githubusercontent.com/74285061/210575702-98f252e0-78c2-4b01-aab9-c770153a797b.png)

이런 방식으로 수정하면 좋을거 같네요!

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingActivity.kt
> +}
xml파일 제외하고 코틀린 파일 맨 아래 줄에 줄바꿈 한번 더 해줘야 lint 안걸리러 같아용!
다른 파일도 그렇습니다!

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/res/layout/activity_onboarding.xml
> +            android:id="@+id/view_pager"
아이디 vp_ 로 시작하는 이름으로 바꿔주면 좋을거같아용

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/res/layout/activity_onboarding.xml
> +            android:layout_marginTop="16dp"
@dimen/spacing16으로 설정해주면 좋을거 같아용

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/res/layout/item_onboarding.xml
> +            android:textSize="18dp"
textAppearance에 textSize값이 포함되어 있어서 따로 textSize 설정해주지 않아도 될 거같네용

2023-01-04 14:30 UTC, YuBeen-Park commented on app/src/main/res/layout/item_onboarding.xml
> +            android:layout_marginBottom="59dp"
margin값 조금 큰거 같아요!
@youngjinc 영진 호출 ㅎㅎ

2023-01-04 16:00 UTC, youngjinc commented on app/src/main/res/layout/item_onboarding.xml
> +            android:layout_marginBottom="59dp"
크네용..

2023-01-05 02:49 UTC, youngjinc approved these changes
리뷰 확인해주세용!

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingActivity.kt
> +    private val mockOnboardingList = listOf(
앞에 mock이라는 키워드는 제거해주세요~

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingActivity.kt
> +        initLayout()
```suggestion

        initLayout()
```

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingActivity.kt
> +                    viewModel?.setPosition(position)
```suggestion
                    viewModel.setPosition(position)
```

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingActivity.kt
> +            TabLayoutMediator(binding.indicator, vpViewPager) { tab, position -> }.attach()
사용되지 않는 변수네용! 변수명을 _로 표시해봅시다~

```suggestion
            TabLayoutMediator(binding.indicator, vpViewPager) { _, _ -> }.attach()
```

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingActivity.kt
> +            binding.vpViewPager.currentItem++
마지막 페이지에서 해당 코드를 실행하면 IndexOutOfBoundsException이 발생할 수 있을 것 같습니다! 함 확인해주세용~

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingAdapter.kt
> +            binding.ivOnboarding.setImageDrawable(binding.root.context.getDrawable(onboarding.image))
데이터 바인딩을 써봅시당!

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
멀티 뷰홀더를 사용할 것이 아니라면 또는 사용할 예정이 없다면 OnBoardingViewHolder 로 바꾸는 것이 좋을 것 같아용~
```suggestion
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): OnBoardingViewHolder {
```

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingAdapter.kt
> +        this.onBoardingList = onboardingList.toList()
이거 toList 붙여준 이유는 무엇일까용?!

2023-01-05 02:49 UTC, youngjinc commented on app/src/main/java/org/keepgoeat/presentation/onboarding/OnBoardingViewModel.kt
> +    }
goooood~~

2023-01-05 09:14 UTC, merged